import { ArrowUpRight, Asterisk, Code2, Braces, Cpu, Database, Trophy } from 'lucide-react'
import { Reveal } from '@/components/portfolio-shell'

const skills = [
  { icon: Braces, title: 'The interface', items: 'React · Next.js · TypeScript · Tailwind CSS · React Native' },
  { icon: Database, title: 'Behind the scenes', items: 'Node.js · Express · Python · SQL · MongoDB · Firebase' },
  { icon: Cpu, title: 'A little intelligence', items: 'TensorFlow.js · NLP · OCR · Automation · AI APIs' },
]
const technologyTicker = [
  { name: 'React', icon: 'react', color: '61DAFB' }, { name: 'Next.js', icon: 'nextdotjs', color: '000000' }, { name: 'TypeScript', icon: 'typescript', color: '3178C6' }, { name: 'Python', icon: 'python', color: '3776AB' }, { name: 'Node.js', icon: 'nodedotjs', color: '339933' }, { name: 'PostgreSQL', icon: 'postgresql', color: '4169E1' }, { name: 'MongoDB', icon: 'mongodb', color: '47A248' }, { name: 'Firebase', icon: 'firebase', color: 'DD2C00' }, { name: 'Tailwind CSS', icon: 'tailwindcss', color: '06B6D4' }, { name: 'React Native', icon: 'react', color: '61DAFB' }, { name: 'Flutter', icon: 'flutter', color: '02569B' }, { name: 'Kotlin', icon: 'kotlin', color: '7F52FF' }, { name: 'OpenAI', icon: 'openai', color: '412991' }, { name: 'TensorFlow.js', icon: 'tensorflow', color: 'FF6F00' },
]
const experiences = [
  { date: 'APR — JUL', company: 'Dejavoo', logo: '/images/dejavoo-logo.svg', initials: 'D', role: 'Data Analyst & QA Testing Intern', copy: 'Built multi-device Python automation for POS terminals, running transaction regression loops and investigating complex testing challenges.', tags: 'Python / uiautomator2 / QA automation' },
  { date: 'NOV 2025', company: 'GyanData', logo: '/images/gyandata-logo.svg', initials: 'G', role: 'Data Science Intern', copy: 'Turned complex financial reports into structured, analysis-ready data. Connected NLP with SQL to streamline enterprise document digitization.', tags: 'Data science / NLP / SQL' },
  { date: 'JUN 2025', company: 'Fourth Dimension', logo: '/images/fourth-dimension-logo.svg', initials: '4D', role: 'Software Developer Intern', copy: 'Shipped an inventory management working model from data modeling and CRUD operations to an integrated, usable interface.', tags: 'Full-stack development / Data modeling' },
]

export function AboutExperience() {
  return <>
    <section id="about" className="about-section"><div className="section-wrap about-grid"><Reveal className="about-heading"><span className="eyebrow section-kicker"><span>02 /</span> THE PERSON BEHIND THE PIXELS</span><h2>Equal parts<br />logic &<br /><span className="serif-word">imagination.</span></h2><Asterisk className="about-star" size={110} strokeWidth={1} aria-hidden="true" /><span className="handwritten">always a work in progress<span className="loading-dots" aria-hidden="true"><i /><i /><i /></span></span></Reveal><div className="about-content"><Reveal><p className="about-lead">I like taking things that feel complicated and making them feel <span>effortless.</span></p><p>I&apos;m Shamuthrika, a Computer Science Engineering student at Chennai Institute of Technology, graduating in 2028. I build across the stack — from the details you see to the systems you don&apos;t.</p><p>My happy place? Somewhere between a tricky algorithm, a hackathon deadline, and that moment when an idea finally comes to life. I care about useful technology, thoughtful interfaces, and learning something new with every build.</p><div className="education-line"><span>B.E. COMPUTER SCIENCE · 2024–2028</span><strong>8.82 <small>CGPA</small></strong></div></Reveal><Reveal><div className="skill-list">{skills.map(({ icon: Icon, title, items }) => <div className="skill-row" key={title}><Icon size={22} strokeWidth={1.5} /><div><h3>{title}</h3><p>{items}</p></div></div>)}</div></Reveal></div></div><Reveal><div className="tech-ticker" aria-label={`Technology stack: ${technologyTicker.map(technology => technology.name).join(', ')}`}><span className="tech-ticker-label">MY TOOLKIT <span>↗</span></span><div className="tech-ticker-window"><div className="tech-ticker-track" aria-hidden="true">{[0, 1].map(copy => <div className="tech-ticker-group" key={copy}>{technologyTicker.map(technology => <span key={technology.name}><img className="tech-mark" src={`https://cdn.simpleicons.org/${technology.icon}/${technology.color}`} alt="" />{technology.name}<i>✦</i></span>)}</div>)}</div></div></div></Reveal></section>
    <section className="milestones section-wrap" aria-label="Achievements"><Reveal><div className="milestone-grid"><div><Code2 size={23} strokeWidth={1.5} /><strong>790<span>+</span></strong><p>LeetCode problems solved</p><small>Knight badge · 2000+ peak rating</small></div><div><Trophy size={23} strokeWidth={1.5} /><strong>Top 2</strong><p>In Tamil Nadu</p><small>ICPC AlgoQueen 2026 · 59th nationally</small></div><div><Asterisk size={24} strokeWidth={1.5} /><strong>4<span>×</span></strong><p>Hackathon finalist</p><small>Building under pressure. Growing through it.</small></div></div></Reveal></section>
    <section id="experience" className="experience-section section-wrap"><Reveal><div className="section-heading"><div><span className="eyebrow section-kicker"><span>03 /</span> LEARNING BY DOING</span><h2>A little more <span className="serif-word">real world.</span></h2></div><a className="text-link" href="/shamuthrika-resume.pdf" target="_blank" rel="noreferrer">The full story <ArrowUpRight size={18} /></a></div></Reveal><div className="experience-list">{experiences.map((experience, index) => <Reveal key={experience.company} delay={index * 0.07}><article className="experience-row"><div className="experience-date"><span>{experience.date}</span><span className="experience-logo"><img src={experience.logo} alt={`${experience.company} logo`} /><b>{experience.initials}</b></span></div><div className="experience-company"><h3>{experience.company}</h3><span>{experience.role}</span></div><div className="experience-description"><p>{experience.copy}</p><span>{experience.tags}</span></div><span className="experience-number">0{index + 1}</span></article></Reveal>)}</div></section>
  </>
}
