export const projects = [
  {
    id: 'chemick', name: 'Chemick', category: 'AI VISION / HEALTHCARE', year: '2026',
    tagline: 'A little scan. A lot of clarity.',
    description: 'An AI vision companion that turns medicine labels and cosmetic ingredients into information people can actually understand.',
    repo: 'Chemick', tags: ['React 19', 'TypeScript', 'Gemini AI'],
    highlight: '7 Indian languages', highlightLabel: 'Multilingual voice readouts',
    features: ['Camera-based product scanning', 'Expiry, ingredient & allergen insights', 'Accessible multilingual voice output'],
    problem: 'Medicine and skincare labels can be dense, technical, and difficult to interpret, especially across language barriers.',
    approach: 'Connect real-time camera input with Gemini-powered product analysis, then present expiry dates, usage instructions, and ingredient explanations in a readable interface with spoken output.',
    scope: 'An informational product-analysis tool, not a substitute for professional medical advice.',
  },
  {
    id: 'sovereign', name: 'Sovereign AI', category: 'AGENTIC AI / SECURITY', year: '2026',
    tagline: 'Autonomy. With boundaries.',
    description: 'A policy-governed control plane for financial AI agents, designed to put human authorization and traceability at the center of execution.',
    repo: 'Sovereign-AI', live: 'https://sovereign-ai-nine.vercel.app', tags: ['React', 'Python', 'FastAPI'],
    highlight: 'Human-in-the-loop', highlightLabel: 'Authorization before execution',
    features: ['Deterministic policy firewall', 'Cryptographic audit ledger', 'Security attack lab & gateway integration'],
    problem: 'Autonomous financial actions need explicit boundaries. A model’s intent alone should not be enough to authorize a transaction.',
    approach: 'Separate agent reasoning from execution through a policy firewall, human authorization, and a cryptographic audit trail. An attack lab explores how those boundaries respond to adversarial scenarios.',
    scope: 'A financial-agent control-plane project; the showcase does not imply certified security or production financial use.',
  },
  {
    id: 'healnet', name: 'HealNet', category: 'RAG / DOCUMENT INTELLIGENCE', year: '2025',
    tagline: 'Less fine print. More clarity.',
    description: 'A health-insurance policy assistant that helps users navigate long documents through natural-language questions and section-referenced answers.',
    repo: 'HealNet_Policy_assist', tags: ['Python', 'FastAPI', 'LangChain', 'RAG'],
    highlight: '100+ page policies', highlightLabel: 'Searchable through conversation',
    features: ['PDF, DOCX & TXT document ingestion', 'Semantic retrieval with policy references', 'Coverage questions & policy recommendations'],
    problem: 'Finding an exclusion, coverage limit, or claim requirement inside a lengthy insurance policy can mean searching through hundreds of pages.',
    approach: 'Extract and chunk documents, create embeddings, retrieve relevant passages, and use an LLM to answer questions with policy-section references. Recommendations help users explore possible coverage gaps.',
    scope: 'An assistance tool: policy wording and insurer confirmation remain the authority for coverage decisions.',
  },
  {
    id: 'permitpro', name: 'PermitPro', category: 'ANDROID / CIVIC TECHNOLOGY', year: '2026',
    tagline: 'Digital permits. Real-world impact.',
    description: 'A street-vendor governance application bringing vendor onboarding, municipal approvals, and on-ground verification into one Android experience.',
    repo: 'PermitPro', tags: ['Kotlin', 'Jetpack Compose', 'MVVM', 'CameraX'],
    highlight: '3 connected portals', highlightLabel: 'Vendor · Administrator · Inspector',
    features: ['Time-limited, one-hour QR passes', 'GPS geofence validation & zone allocation', 'Approval, verification & enforcement flows'],
    problem: 'Street-vending permits involve multiple people and disconnected processes, from an application to field verification.',
    approach: 'Build role-specific portals with Jetpack Compose and MVVM. Vendors apply for assigned zones, administrators review applications, and inspectors validate time-limited QR passes against GPS boundaries.',
    scope: 'A governance application project; no municipal deployment is claimed.',
  },
  {
    id: 'cascade', name: 'CASCADE', category: 'SIMULATION / DECISION SUPPORT', year: '2026',
    tagline: 'What fails next? What helps most?',
    description: 'A counterfactual infrastructure-analysis prototype for exploring cascading failures and comparing corrective actions before a second shock hits.',
    repo: 'cascade---new', tags: ['TypeScript', 'Vite', 'Simulation'],
    highlight: '3 case-study domains', highlightLabel: 'Grid · Hospital · Data center',
    features: ['Cascade propagation & impact calculation', 'Counterfactual intervention comparison', 'Independent second-shock resilience checks'],
    problem: 'An infrastructure failure rarely happens in isolation. Operators need to reason about downstream effects and the trade-offs between possible interventions.',
    approach: 'Run modelled networks through propagation, impact, candidate-action, and recommendation stages. Verify the proposed action against an independent secondary shock using Tamil Nadu grid, Chennai hospital, and data-center case studies.',
    scope: 'Decision-support prototype only—not live SCADA, a full power-flow simulator, or a system that controls infrastructure. Modelled and derived results are distinguished from verified evidence.',
  },
  {
    id: 'civart', name: 'CivArt Guardian', category: 'FLUTTER / HERITAGE PRESERVATION', year: '2025',
    tagline: 'Old stories. New ways to protect them.',
    description: 'A Flutter application inspired by a Smart India Hackathon problem statement, connecting public damage reports with government heritage-site portals.',
    repo: 'CivArtGuardian_Flutter_APP', tags: ['Flutter', 'Dart', 'Mobile'],
    highlight: 'Online + offline', highlightLabel: 'Reporting beyond reliable connectivity',
    features: ['Heritage sculpture damage reporting', 'Public-to-government portal interaction', 'Designed for online and offline use'],
    problem: 'Damage to heritage sculptures needs a clear path from public observation to the people responsible for preservation.',
    approach: 'Use a cross-platform Flutter app as the reporting bridge between visitors and government portals, with online and offline usage in mind.',
    scope: 'An SIH-inspired application project; participation awards or government adoption are not claimed.',
  },
] as const

export type PortfolioProject = (typeof projects)[number]
